<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = array(
            array("id" => 1, "name" => "desdunes", "department_id" => 4),
            array("id" => 2, "name" => "dessalines", "department_id" => 4),
            array("id" => 3, "name" => "grande saline", "department_id" => 4),
            array("id" => 4, "name" => "petite-riviere de l'artibonite", "department_id" => 4),
            array("id" => 5, "name" => "ennery", "department_id" => 4),
            array("id" => 6, "name" => "gonaïves", "department_id" => 4),
            array("id" => 7, "name" => "l'estere", "department_id" => 4),
            array("id" => 8, "name" => "gros-morne", "department_id" => 4),
            array("id" => 9, "name" => "anse-rouge", "department_id" => 4),
            array("id" => 10, "name" => "terre-neuve", "department_id" => 4),
            array("id" => 11, "name" => "marmelade", "department_id" => 4),
            array("id" => 12, "name" => "saint-michel", "department_id" => 4),
            array("id" => 13, "name" => "la chapelle", "department_id" => 4),
            array("id" => 14, "name" => "saint-marc", "department_id" => 4),
            array("id" => 15, "name" => "verrettes", "department_id" => 4),
            array("id" => 16, "name" => "cerca-la-source", "department_id" => 7),
            array("id" => 17, "name" => "thomassique", "department_id" => 7),
            array("id" => 18, "name" => "cerca-carvajal", "department_id" => 7),
            array("id" => 19, "name" => "hinche", "department_id" => 7),
            array("id" => 20, "name" => "maïssade", "department_id" => 7),
            array("id" => 21, "name" => "thomonde", "department_id" => 7),
            array("id" => 22, "name" => "belladère", "department_id" => 7),
            array("id" => 23, "name" => "lascahobas", "department_id" => 7),
            array("id" => 24, "name" => "savanette", "department_id" => 7),
            array("id" => 25, "name" => "boucan-carre", "department_id" => 7),
            array("id" => 26, "name" => "mirebalais", "department_id" => 7),
            array("id" => 27, "name" => "saut-d'eau", "department_id" => 7),
            array("id" => 28, "name" => "corail", "department_id" => 5),
            array("id" => 29, "name" => "roseaux", "department_id" => 5),
            array("id" => 30, "name" => "beaumont", "department_id" => 5),
            array("id" => 31, "name" => "pestel", "department_id" => 5),
            array("id" => 32, "name" => "abricots", "department_id" => 5),
            array("id" => 33, "name" => "bonbon", "department_id" => 5),
            array("id" => 34, "name" => "jérémie", "department_id" => 5),
            array("id" => 35, "name" => "chambellan", "department_id" => 5),
            array("id" => 36, "name" => "moron", "department_id" => 5),
            array("id" => 37, "name" => "anse-à-veau", "department_id" => 10),
            array("id" => 38, "name" => "arnaud", "department_id" => 10),
            array("id" => 39, "name" => "l'asile", "department_id" => 10),
            array("id" => 40, "name" => "petit-trou", "department_id" => 10),
            array("id" => 41, "name" => "plaisance du sud", "department_id" => 10),
            array("id" => 42, "name" => "fonds-des-negres", "department_id" => 10),
            array("id" => 43, "name" => "miragoane", "department_id" => 10),
            array("id" => 44, "name" => "paillant", "department_id" => 10),
            array("id" => 45, "name" => "petite riviere de nippes", "department_id" => 10),
            array("id" => 46, "name" => "borgne", "department_id" => 2),
            array("id" => 47, "name" => "port-margot", "department_id" => 2),
            array("id" => 48, "name" => "cap-haïtien", "department_id" => 2),
            array("id" => 49, "name" => "limonade", "department_id" => 2),
            array("id" => 50, "name" => "quartier-morin", "department_id" => 2),
            array("id" => 51, "name" => "bas-limbe", "department_id" => 2),
            array("id" => 52, "name" => "limbe", "department_id" => 2),
            array("id" => 53, "name" => "pilate", "department_id" => 2),
            array("id" => 54, "name" => "plaisance", "department_id" => 2),
            array("id" => 55, "name" => "la victoire", "department_id" => 2),
            array("id" => 56, "name" => "pignon", "department_id" => 2),
            array("id" => 57, "name" => "ranquitte", "department_id" => 2),
            array("id" => 58, "name" => "dondon", "department_id" => 2),
            array("id" => 59, "name" => "saint-raphaël", "department_id" => 2),
            array("id" => 60, "name" => "ferrier", "department_id" => 9),
            array("id" => 61, "name" => "fort-liberté", "department_id" => 9),
            array("id" => 62, "name" => "perches", "department_id" => 9),
            array("id" => 63, "name" => "capotille", "department_id" => 9),
            array("id" => 64, "name" => "mont-organisé", "department_id" => 9),
            array("id" => 65, "name" => "ouanaminthe", "department_id" => 9),
            array("id" => 66, "name" => "sainte-suzanne", "department_id" => 9),
            array("id" => 67, "name" => "terrier-rouge", "department_id" => 9),
            array("id" => 68, "name" => "caracol", "department_id" => 9),
            array("id" => 69, "name" => "trou-du-nord", "department_id" => 9),
            array("id" => 70, "name" => "carice", "department_id" => 9),
            array("id" => 71, "name" => "mombin-crochu", "department_id" => 9),
            array("id" => 72, "name" => "vallières", "department_id" => 9),
            array("id" => 73, "name" => "bassin bleu", "department_id" => 8),
            array("id" => 74, "name" => "chansolme", "department_id" => 8),
            array("id" => 75, "name" => "la tortue", "department_id" => 8),
            array("id" => 76, "name" => "port-de-paix", "department_id" => 8),
            array("id" => 77, "name" => "arcahaie", "department_id" => 1),
            array("id" => 78, "name" => "cabaret", "department_id" => 1),
            array("id" => 79, "name" => "cornillon", "department_id" => 1),
            array("id" => 80, "name" => "croix-des-bouquets", "department_id" => 1),
            array("id" => 81, "name" => "thomazeau", "department_id" => 1),
            array("id" => 82, "name" => "fonds-verrettes", "department_id" => 1),
            array("id" => 83, "name" => "ganthier", "department_id" => 1),
            array("id" => 84, "name" => "anse-a-galets", "department_id" => 1),
            array("id" => 85, "name" => "pointe-a-raquette", "department_id" => 1),
            array("id" => 86, "name" => "grand-goave", "department_id" => 1),
            array("id" => 87, "name" => "leogane", "department_id" => 1),
            array("id" => 88, "name" => "petit-goave", "department_id" => 1),
            array("id" => 89, "name" => "carrefour", "department_id" => 1),
            array("id" => 90, "name" => "cité-soleil", "department_id" => 1),
            array("id" => 91, "name" => "delmas", "department_id" => 1),
            array("id" => 92, "name" => "tabarre", "department_id" => 1),
            array("id" => 93, "name" => "gressier", "department_id" => 1),
            array("id" => 94, "name" => "kenscoff", "department_id" => 1),
            array("id" => 95, "name" => "pétion-ville", "department_id" => 1),
            array("id" => 96, "name" => "port-au-prince", "department_id" => 1),
            array("id" => 97, "name" => "aquin", "department_id" => 3),
            array("id" => 98, "name" => "cavaillon", "department_id" => 3),
            array("id" => 99, "name" => "saint-louis du sud", "department_id" => 3),
            array("id" => 100, "name" => "chardonnieres", "department_id" => 3),
            array("id" => 101, "name" => "les anglais", "department_id" => 3),
            array("id" => 102, "name" => "tiburon", "department_id" => 3),
            array("id" => 103, "name" => "coteaux", "department_id" => 3),
            array("id" => 104, "name" => "port-a-piment", "department_id" => 3),
            array("id" => 105, "name" => "roche-a-bateau", "department_id" => 3),
            array("id" => 106, "name" => "port-salut", "department_id" => 3),
            array("id" => 107, "name" => "arniquet", "department_id" => 3),
            array("id" => 108, "name" => "saint-jean du sud", "department_id" => 3),
            array("id" => 109, "name" => "bainet", "department_id" => 6),
            array("id" => 110, "name" => "cotes de fer", "department_id" => 6),
            array("id" => 111, "name" => "anse-a-pitre", "department_id" => 6),
            array("id" => 112, "name" => "belle-anse", "department_id" => 6),
            array("id" => 113, "name" => "grand-gosier", "department_id" => 6),
            array("id" => 114, "name" => "thiotte", "department_id" => 6),
            array("id" => 115, "name" => "jacmel", "department_id" => 6),
            array("id" => 116, "name" => "la vallee de jacmel", "department_id" => 6),
            array("id" => 117, "name" => "cayes-jacmel", "department_id" => 6),
            array("id" => 118, "name" => "marigot", "department_id" => 6),
            array("id" => 119, "name" => "acul-du-nord", "department_id" => 2),
            array("id" => 120, "name" => "anse-à-foleur", "department_id" => 8),
            array("id" => 121, "name" => "baie-de-henne", "department_id" => 8),
            array("id" => 122, "name" => "dame-marie", "department_id" => 5),
            array("id" => 123, "name" => "grand-boucan", "department_id" => 10),
            array("id" => 124, "name" => "île-à-vache", "department_id" => 3),
            array("id" => 125, "name" => "les cayes", "department_id" => 3),
            array("id" => 126, "name" => "plaine-du-nord", "department_id" => 2),
            array("id" => 127, "name" => "grande-rivière-du-nord", "department_id" => 2),
            array("id" => 128, "name" => "bahon", "department_id" => 2)
        );

        foreach ($cities as $key => $city) {
            City::create($city);
        }
    }
}
